"""Adding posts table

Revision ID: e8fffc623398
Revises: 1c3c669ef7c6
Create Date: 2022-10-30 23:56:46.053491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fffc623398'
down_revision = '1c3c669ef7c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
